### PR TITLE
[IMP] Upgrade to new quality tools and base

### PR DESCRIPTION
**Pull request by lasley**
Depends on LasLabs/docker-quality-tools#1

### CODE REVIEW

**Comment by lasley** [comment]
Switched DQT to master now that it's merged

**Review by tedsalmon — CHANGES_REQUESTED** [review]
Build is failing (sadpanda)
```
ERROR: unsatisfiable constraints:
"python" (missing):
required by: world["python"]
The command '/bin/sh -c apk add --no-cache build-base                        "$PYTHON_PACKAGE"                        "${PYTHON_PACAKAGE}-dev"' returned a non-zero code: 1
```

**Comment by lasley** [comment]
Fixed! Seeing as it was just a typo, I squashed too.

**Review by tedsalmon — CHANGES_REQUESTED** [review]
Build is still failing:
```
ERROR: unsatisfiable constraints:
"python3" (missing):
required by: world["python3"]
"python3"-dev (missing):
required by: world["python3"-dev]
The command '/bin/sh -c apk add --no-cache build-base                        "$PYTHON_PACKAGE"                        "${PYTHON_PACKAGE}-dev"' returned a non-zero code: 2
```

**Comment by lasley** [comment]
Ahhh so it was getting the inner quotes from the travis file on the build args. I went ahead and simplified some things while I was at it + updated for Alpine 3.5, which makes a more clear distinction between the python packages.

Should be good now.

**Review by tedsalmon — APPROVED** [review]

**Pull request merged**
